services:
  stats-db:
    image: postgres:16.1
    container_name: stats_db
    ports:
      - "6541:5432"
    environment:
      - POSTGRES_USER=stats
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=stats
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  ewm-db:
    image: postgres:16.1
    container_name: ewm_db
    ports:
      - "6542:5432"
    environment:
      - POSTGRES_USER=ewm
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=ewm
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10

  user-db:
    image: postgres:16.1
    container_name: user_db
    ports:
      - "6543:5432"
    environment:
      - POSTGRES_USER=users
      - POSTGRES_PASSWORD=1234
      - POSTGRES_DB=users
    healthcheck:
      test: pg_isready -q -d $$POSTGRES_DB -U $$POSTGRES_USER
      timeout: 5s
      interval: 5s
      retries: 10