spring:
  datasource:
    url: jdbc:postgresql://localhost:6545/comments
    username: comments
    password: 1234
    driver-class-name: org.postgresql.Driver
  sql:
    init:
      mode: always
  jpa:
    hibernate:
      ddl-auto: none
    properties:
      hibernate:
        format_sql: true
    show-sql: true

logging:
  level:
    root: INFO
    org.springframework.web: DEBUG
    org.springframework.transaction: INFO
    org.springframework.transaction.interceptor: TRACE
    org.springframework.orm.jpa: INFO
    org.springframework.orm.jpa.JpaTransactionManager: DEBUG
    org.slf4j: DEBUG
    ru.practicum: DEBUG
    org.hibernate.SQL: DEBUG
    org.hibernate.type.descriptor.sql.BasicBinder: TRACE

discovery:
  services:
    stats-server-id: stats-server