kafka:
  properties:
    bootstrap-servers": localhost:9092
  consumer:
    properties:
      group-id: aggregator
  topics:
    user-actions: stats.user-actions.v1
    events-similarity: stats.events-similarity.v1

grpc:
  server:
    port: 0