collector:
  kafka:
    properties:
      bootstrap-servers": localhost:9092
    consumer:
      properties:
        "group-id": aggregator
    topics:
      events-similarity: stats.events-similarity.v1

grpc:
  server:
    port: 0