spring:
  cloud:
    gateway:
      discovery.locator.enabled: true
      routes:
        - id: user_service_route
          uri: lb://user-service
          predicates:
            - Path=/admin/users/**

        - id: request_service_route
          uri: lb://request-service
          predicates:
            - Path=/users/*/requests/**

        - id: admin_comment_service_route
          uri: lb://comment-service
          predicates:
            - Path=/admin/comments/**

        - id: public_comment_service_route
          uri: lb://comment-service
          predicates:
            - Path=/events/*/comments

        - id: user_comment_service_route
          uri: lb://comment-service
          predicates:
            - Path=/users/*/comments, /users/*/events/*/comments/**

        - id: admin_category_service_route
          uri: lb://category-service
          predicates:
            - Path=/admin/categories/**

        - id: public_category_service_route
          uri: lb://category-service
          predicates:
            - Path=/categories/**

        - id: admin_event_service_route
          uri: lb://event-service
          predicates:
              - Path=/admin/events/**

        - id: public_event_service_route
          uri: lb://event-service
          predicates:
            - Path=/events/**

        - id: user_event_service_route
          uri: lb://event-service
          predicates:
            - Path=/users/*/events/**

        - id: public_compilation_service_route
          uri: lb://event-service
          predicates:
            - Path=/compilations/**

        - id: admin_compilation_service_route
          uri: lb://event-service
          predicates:
            - Path=/admin/compilations/**

management:
  endpoints:
    web:
      exposure:
        include: "*"
  endpoint:
    gateway:
      enabled: true

logging:
  level:
    org.springframework.web: DEBUG
    org.springframework.http: TRACE
    org.slf4j: DEBUG
    ru.practicum: DEBUG